name: Maven Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TESTINGBOT_KEY: ${{ secrets.TESTINGBOT_KEY }}
      TESTINGBOT_SECRET: ${{ secrets.TESTINGBOT_SECRET }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test with Maven
      run: mvn clean test